apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-premium
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
